---
- name: Linux Health Check
  hosts: linux_servers
  gather_facts: true

  tasks:

    - name: Check disk
      ansible.builtin.command: df -h
      register: disk
      changed_when: false
      when: check_type in ['disk', 'all']

    - name: Check CPU
      ansible.builtin.debug:
        msg: "CPU Cores: {{ ansible_processor_vcpus }}"
      when: check_type in ['cpu', 'all']

    - name: Check memory
      ansible.builtin.debug:
        msg: "Total RAM: {{ ansible_memtotal_mb }} MB"
      when: check_type in ['memory', 'all']

    - name: Display disk report
      ansible.builtin.debug:
        msg: "{{ disk.stdout }}"
      when: check_type in ['disk', 'all']
